<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles single entries, but only exists for the sake of child theme forward compatibility.

/* add yarpp only after single posts */
/* Disabled YARPP 12/16/14 performance problems */

/*
add_filter('genesis_after_post_content', 'add_yarpp');
function add_yarpp($content) {
    if (is_singular()) {
        return $content.related_posts();
    } else {
        return $content;
    }
}
 * 
 */

genesis();
